[project]
name = 'Water-Quality-Monitoring-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sensor-data-management]
path = 'contracts/sensor-data-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.water-quality-nft]
path = 'contracts/water-quality-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
